#!/bin/bash

sudo apt-get install -y avrdude python-dev python-rpi.gpio minicom

echo "install avrdude autoreset"

sudo ln -s /home/pi/avrdude-rpi/autoreset /usr/bin/autoreset

if [ ! -f /usr/bin/avrdude-original ]; then 
	sudo mv /usr/bin/avrdude /usr/bin/avrdude-original
fi

sudo ln -s /home/pi/avrdude-rpi/avrdude-autoreset /usr/bin/avrdude




