#!/bin/sh
########### Put in ISP mode ###########
# ISP set low
echo "out" > /sys/class/gpio/gpio18/direction
echo "0" > /sys/class/gpio/gpio18/value
# RST set low
echo "out" > /sys/class/gpio/gpio17/direction
echo "0" > /sys/class/gpio/gpio17/value
sleep 0.5
echo "1" > /sys/class/gpio/gpio17/value
sleep 0.5
echo "1" > /sys/class/gpio/gpio18/value
