#!/bin/sh

#sudo apt-get install lpc21isp
#wget https://raw.githubusercontent.com/Smoothieware/Smoothieware/edge/bootloader/DFU-Bootloader.hex
#lpc21isp -wipe DFU-Bootloader.hex /dev/ttyAMA0 230400 12000

#echo "18" > /sys/class/gpio/export
#echo "17" > /sys/class/gpio/export


########### Put in ISP mode ###########
# ISP set low
echo "out" > /sys/class/gpio/gpio18/direction
echo "0" > /sys/class/gpio/gpio18/value

# RST set low
echo "out" > /sys/class/gpio/gpio17/direction
echo "0" > /sys/class/gpio/gpio17/value

sleep 0.5

echo "1" > /sys/class/gpio/gpio17/value

sleep 0.5

echo "1" > /sys/class/gpio/gpio18/value

########### Program ###########
wget https://raw.githubusercontent.com/Smoothieware/Smoothieware/edge/bootloader/DFU-Bootloader.hex
lpc21isp -wipe DFU-Bootloader.hex /dev/ttyAMA0 230400 12000

########### Restart ###########
echo "0" > /sys/class/gpio/gpio17/value
sleep 0.5
echo "1" > /sys/class/gpio/gpio17/value





#echo "1" > /sys/class/gpio/gpio17/value 
#echo "18" > /sys/class/gpio/unexport



# Use Pin 17(Reset) and 18(ISP)
# echo "17" > /sys/class/gpio/export
# echo "out" > /sys/class/gpio/gpio17/direction
# echo "1" > /sys/class/gpio/gpio17/value 
# echo "0" > /sys/class/gpio/gpio17/value
# echo "17" > /sys/class/gpio/unexport

